### ISSUE TITLE
Doesn't support new syntax for db.Type syntax

### ISSUE THREAD

**Issue by RIP21** [gabrielcolson/intellij-prisma#14]
So-called native database type attributes are not supported. For reference: https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#postgresql
![image](https://user-images.githubusercontent.com/3940079/111553053-e0fbdc80-8783-11eb-8b0f-b3fd63b3078d.png)

**Comment by geisterfurz007** [comment]
Hey, I would like to look into this if possible. If you know where I have to look for this, that would be awesome @gabrielcolson!

**Comment by gabrielcolson** [comment]
Hey @geisterfurz007, thanks for taking the time to take a look at this! In order to support this feature, you probably want to take a look at the Prisma syntax definition in `src/main/java/org/intellij/sdk/language/Prisma.bnf` et `src/main/java/org/intellij/sdk/language/Prisma.flex`. Let me know if you need more information!

**Comment by gabrielcolson** [comment]
Hello @RIP21 

This feature has been implemented in #15 by @geisterfurz007 

The 1.2.4 version has been submitted to the marketplace and is currently being reviewed. You can expect it to be released this week ;)
